/**
 * Weekly pattern analysis for the self-improvement loop.
 *
 * For each auto-posting account, aggregates engagement by post structure type,
 * stores the result in `pattern_stats/{accountId}`, and the generator then
 * prefers the best-performing patterns and avoids the worst. When enough posts
 * exist, it also asks the LLM for CONTENT-level insights (topics/traits) and
 * auto-generates discovery keywords, all stored alongside for the generator.
 *
 *   npm run analyze:patterns            # with LLM content insights
 *   npm run analyze:patterns -- --no-insights
 */
import { adminDb } from "@/lib/firebase/admin";
import type { PostDoc } from "@/lib/types";
import { computePatternAnalysis } from "@/lib/pattern";
import {
  generateContentInsights,
  generateDiscoveryKeywords,
} from "@/lib/services/insight-service";
import {
  getAccounts,
  getPatternStats,
  savePatternStats,
} from "@/lib/services/firestore.server";
import { DateTime } from "luxon";
import {
  belongsToCharacterVersion,
  getCharacterVersion,
} from "@/lib/character-version";

const LOOKBACK_DAYS = 30;
const MIN_POSTS = 5;
const MIN_POSTS_FOR_INSIGHTS = 15;
const MIN_POSTS_FOR_KEYWORDS = 10;
const INSIGHT_FRESH_DAYS = 7;
const KEYWORD_REFRESH_DAYS = 14;

async function fetchRecentPostsForAccount(
  accountId: string,
  days: number,
): Promise<PostDoc[]> {
  const start = DateTime.utc().minus({ days }).toISO()!;
  try {
    const snapshot = await adminDb
      .collection("posts")
      .where("account_id", "==", accountId)
      .where("created_at", ">=", start)
      .get();
    return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }) as PostDoc);
  } catch (error) {
    const message = (error as Error).message ?? "";
    if (!message.includes("requires an index")) throw error;
    const fallback = await adminDb
      .collection("posts")
      .where("account_id", "==", accountId)
      .get();
    const threshold = DateTime.fromISO(start).toMillis();
    return fallback.docs
      .map((doc) => ({ id: doc.id, ...doc.data() }) as PostDoc)
      .filter(
        (post) => DateTime.fromISO(post.created_at).toMillis() >= threshold,
      );
  }
}

function insightsAreFresh(existing: { content_insights?: { generatedAt: string } } | null): boolean {
  if (!existing?.content_insights?.generatedAt) return false;
  const generated = DateTime.fromISO(existing.content_insights.generatedAt);
  return (
    generated.isValid &&
    DateTime.utc().diff(generated, "days").days < INSIGHT_FRESH_DAYS
  );
}

function keywordsNeedRefresh(account: {
  discoveryKeywords?: string[];
  discoveryKeywordsAutoGenerated?: boolean;
  discoveryKeywordsUpdatedAt?: string;
}): boolean {
  if (!account.discoveryKeywords || account.discoveryKeywords.length === 0) {
    return true;
  }
  if (!account.discoveryKeywordsAutoGenerated) return false;
  if (!account.discoveryKeywordsUpdatedAt) return true;
  const updated = DateTime.fromISO(account.discoveryKeywordsUpdatedAt);
  return (
    updated.isValid &&
    DateTime.utc().diff(updated, "days").days >= KEYWORD_REFRESH_DAYS
  );
}

async function main() {
  const accounts = (await getAccounts()).filter(
    (account) => account.autoPostEnabled === true,
  );
  const skipInsights = process.argv.includes("--no-insights");
  let updated = 0;
  let insightsGenerated = 0;

  for (const account of accounts) {
    try {
      const characterVersion = getCharacterVersion(account);
      const posts = (await fetchRecentPostsForAccount(account.id, LOOKBACK_DAYS))
        .filter((post) => belongsToCharacterVersion(post, characterVersion));
      if (posts.length < MIN_POSTS) {
        console.log(
          `[Pattern] ${account.handle}: only ${posts.length} posts for character v${characterVersion} in ${LOOKBACK_DAYS}d; skipping.`,
        );
        continue;
      }
      const analysis = computePatternAnalysis(posts, account.id);
      analysis.character_version = characterVersion;

      if (!skipInsights && posts.length >= MIN_POSTS_FOR_INSIGHTS) {
        const existing = await getPatternStats(account.id);
        if (
          existing &&
          getCharacterVersion(existing) === characterVersion &&
          insightsAreFresh(existing)
        ) {
          analysis.content_insights = existing.content_insights;
        } else {
          try {
            const insights = await generateContentInsights(
              posts,
              account.concept,
            );
            if (insights) {
              analysis.content_insights = insights;
              insightsGenerated += 1;
            }
          } catch (error) {
            console.warn(
              `[Pattern] Content insights skipped for ${account.handle}:`,
              (error as Error).message,
            );
          }
        }
      }

      if (
        !skipInsights &&
        posts.length >= MIN_POSTS_FOR_KEYWORDS &&
        keywordsNeedRefresh(account)
      ) {
        try {
          const keywords = await generateDiscoveryKeywords(
            posts,
            account.concept,
          );
          if (keywords && keywords.length > 0) {
            await adminDb.collection("accounts").doc(account.id).update({
              discoveryKeywords: keywords,
              discoveryKeywordsAutoGenerated: true,
              discoveryKeywordsUpdatedAt: DateTime.utc().toISO()!,
              updated_at: DateTime.utc().toISO()!,
            });
            console.log(
              `[Pattern] Auto-set discovery keywords for ${account.handle}: ${keywords.join(", ")}`,
            );
          }
        } catch (error) {
          console.warn(
            `[Pattern] Discovery keywords skipped for ${account.handle}:`,
            (error as Error).message,
          );
        }
      }

      await savePatternStats(account.id, analysis);
      updated += 1;
      console.log(
        `[Pattern] ${account.handle} v${characterVersion}: ${analysis.patterns.length} patterns over ${analysis.analyzedPosts} posts (median ${(analysis.accountMedianEngagementRate ?? 0) * 100}%)${analysis.content_insights ? " +content insights" : ""}.`,
      );
    } catch (error) {
      console.error(`[Pattern] Failed for ${account.handle}:`, error);
    }
  }

  console.log(
    `[Pattern] Updated ${updated} accounts (${insightsGenerated} content insights generated).`,
  );
}

main().catch((error) => {
  console.error("[Pattern] Unexpected failure:", error);
  process.exit(1);
});
