import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { DateTime } from "luxon";
import { adminDb } from "@/lib/firebase/admin";
import { getAccounts, getAccount, getUsableDraftsByAccountId, fetchRecentPosts } from "@/lib/services/firestore.server";
import { createAgentDrafts } from "@/lib/services/draft-service";
import { runIdempotentOperation } from "@/lib/services/agent-operation-service";
import { getCharacterVersion } from "@/lib/character-version";
import { updateAccount } from "@/lib/services/account-service";
import { syncPostsForAllAccounts } from "@/lib/services/sync-service";
import { getProductPool, createProductPoolItem, updateProductPoolItem } from "@/lib/services/product-pool-service";
import { publishExistingDraft } from "@/lib/services/scheduler-service";
import { normalizeProductCatalogInput, productCatalogUpdateSchema } from "@/lib/product-catalog-schema";
import { DEFAULT_AFFILIATE_CONTEXT_KEY, getAffiliateDistributionRuntimeState, getProjectContext, updateProjectContext } from "@/lib/services/project-context-service";
import { getProductPerformanceWork } from "@/lib/services/affiliate-tracking-service";
import { listAffiliateOffers, getAffiliateOffer, saveAffiliateOffer, archiveAffiliateOffer, getAffiliateReplyWork, createAffiliateReplyDraft, publishAffiliateReply, reconcileAffiliateReply, updateAffiliateOfferPerformance } from "@/lib/services/affiliate-offer-service";
import { getOwnedContentDistributionWork, listOwnedContentItems, listOwnedContentSources, saveOwnedContentItem, saveOwnedContentSource, syncOwnedContentItems } from "@/lib/services/owned-content-service";

const text = (value: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] });
const page = z.number().int().min(1).default(1); const limit = z.number().int().min(1).max(50).default(20);
const write = { idempotencyKey: z.string().min(1).max(128) };
const projectContextKey = z.string().trim().min(1).max(128).regex(/^[A-Za-z0-9._-]+$/).default(DEFAULT_AFFILIATE_CONTEXT_KEY);
const performanceContextKey = z.string().trim().min(1).max(128).regex(/^[A-Za-z0-9._-]+$/).default("affiliate_product_performance_v1");
const affiliateOfferKind = z.enum(["amazon_product","service","lead","subscription","digital_product","owned_product"]);
const affiliateOfferStatus = z.enum(["candidate","pending_approval","approved","active","paused","archived"]);
const ownedContentSourceType = z.enum(["website","note","newsletter","other"]);
const ownedContentSourceStatus = z.enum(["active","paused","archived"]);
const ownedContentItemStatus = z.enum(["candidate","active","paused","archived"]);
const ownedContentSourceUpdateSchema = z.object({
  source_type: ownedContentSourceType.optional(),
  provider: z.string().trim().min(1).max(100).optional(),
  external_source_id: z.string().trim().max(300).optional(),
  name: z.string().trim().min(1).max(300).optional(),
  base_url: z.union([z.string().url().max(1500), z.literal("")]).optional(),
  language: z.string().trim().max(32).optional(),
  themes: z.array(z.string().trim().min(1).max(120)).max(100).optional(),
  allowed_platforms: z.array(z.enum(["x","threads"])).max(10).optional(),
  allowed_account_ids: z.array(z.string().trim().min(1).max(256)).max(100).optional(),
  persona_fits: z.array(z.string().trim().min(1).max(300)).max(100).optional(),
  distribution_hooks: z.array(z.string().trim().min(1).max(1000)).max(100).optional(),
  weight: z.number().min(0.1).max(10).optional(),
  status: ownedContentSourceStatus.optional(),
}).passthrough();
const ownedContentItemUpdateSchema = z.object({
  source_id: z.string().trim().min(1).max(256).optional(),
  external_content_id: z.string().trim().max(512).optional(),
  title: z.string().trim().min(1).max(500).optional(),
  canonical_url: z.string().url().max(2000).optional(),
  status: ownedContentItemStatus.optional(),
  themes: z.array(z.string().trim().min(1).max(120)).max(100).optional(),
  allowed_account_ids: z.array(z.string().trim().min(1).max(256)).max(100).optional(),
  persona_fits: z.array(z.string().trim().min(1).max(300)).max(100).optional(),
  distribution_hooks: z.array(z.string().trim().min(1).max(1000)).max(100).optional(),
  published_at: z.string().trim().max(64).optional(),
  notes: z.string().trim().max(5000).optional(),
}).passthrough();
const affiliateOfferUpdateSchema = z.object({
  kind: affiliateOfferKind.optional(),
  network: z.string().trim().min(1).max(100).optional(),
  advertiser: z.string().trim().max(300).optional(),
  programId: z.string().trim().max(300).optional(),
  sourceProductId: z.string().trim().max(256).optional(),
  title: z.string().trim().min(1).max(300).optional(),
  description: z.string().trim().max(5000).optional(),
  destinationUrl: z.union([z.string().url().max(1500), z.literal("")]).optional(),
  affiliateUrl: z.union([z.string().url().max(2000), z.literal("")]).optional(),
  category: z.string().trim().max(160).optional(),
  themes: z.array(z.string().trim().min(1).max(120)).max(50).optional(),
  conversionAction: z.string().trim().max(500).optional(),
  reward: z.object({
    amount: z.number().min(0).optional(),
    currency: z.string().trim().max(16).optional(),
    type: z.enum(["fixed","percentage","variable"]).optional(),
    description: z.string().trim().max(500).optional(),
  }).optional(),
  status: affiliateOfferStatus.optional(),
  allowedPlatforms: z.array(z.enum(["x","threads"])).max(10).optional(),
  allowedAccountIds: z.array(z.string().trim().min(1).max(256)).max(100).optional(),
  personaFits: z.array(z.string().trim().min(1).max(300)).max(100).optional(),
  promoHooks: z.array(z.string().trim().min(1).max(1000)).max(100).optional(),
  prohibitedClaims: z.array(z.string().trim().min(1).max(1000)).max(100).optional(),
  disclosureText: z.string().trim().max(500).optional(),
  validFrom: z.string().trim().max(64).optional(),
  validUntil: z.string().trim().max(64).optional(),
  sourceUrl: z.union([z.string().url().max(1500), z.literal("")]).optional(),
  notes: z.string().trim().max(5000).optional(),
  offerCooldownMinutes: z.number().int().min(0).max(43200).optional(),
  performance: z.record(z.string(), z.unknown()).optional(),
}).passthrough();
const projectContextChanges = z.object({
  title: z.string().trim().min(1).max(300).optional(),
  content: z.string().trim().min(1).max(30000).optional(),
  status: z.enum(["active", "inactive"]).optional(),
  version: z.union([z.number().int().min(1), z.string().trim().min(1).max(64)]).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
}).passthrough();
async function assertUpdated(ref: FirebaseFirestore.DocumentReference, expected: string) {
  const snap = await ref.get(); if (!snap.exists) throw new Error("Document not found.");
  if (snap.data()?.updated_at !== expected) throw new Error("updated_at conflict: refresh and retry.");
  return snap;
}

const SERVER_VERSION = "1.4.0";
const MCP_TOOLS = [
  "get_system_health","list_accounts","get_account","get_generation_work","list_drafts","list_recent_posts","get_schedule","list_guidance",
  "get_project_context","update_project_context","list_products","get_product_discovery_work","get_product_performance_work",
  "list_owned_content_sources","save_owned_content_source","list_owned_content_items","save_owned_content_item","sync_owned_content_items","get_owned_content_distribution_work",
  "create_drafts","update_draft","delete_draft","publish_draft","update_account","sync_posts","save_product","archive_product","save_guidance","delete_guidance",
  "list_affiliate_offers","get_affiliate_offer","save_affiliate_offer","archive_affiliate_offer","get_affiliate_reply_work",
  "create_affiliate_reply_draft","publish_affiliate_reply","reconcile_affiliate_reply","update_affiliate_offer_performance"
] as const;

export function createTweetsMcpServer() {
  const server = new McpServer({ name: "tweets-operator", version: SERVER_VERSION });
  server.registerTool("get_system_health", { description: "Summarize connection and current-version draft inventory. Read only.", inputSchema: {} , annotations: { readOnlyHint: true }}, async () => {
    const accounts = await getAccounts(); const [inventory, affiliateDistributionRuntime] = await Promise.all([Promise.all(accounts.map(async (a) => ({ accountId: a.id, usableDrafts: (await getUsableDraftsByAccountId(a.id, getCharacterVersion(a))).length }))), getAffiliateDistributionRuntimeState()]);
    return text({ status: "ok", serverVersion: SERVER_VERSION, accounts: accounts.length, inventory, toolCount: MCP_TOOLS.length, tools: MCP_TOOLS, capabilities: { projectContext: true, productDiscoveryWork: true, productPerformanceWork: true, affiliateProductSchema: "v2", affiliateTracking: true, affiliateOfferCatalog: true, affiliateReplyWork: true, affiliateReplyTracking: true, affiliateDistributionContext: true, promoReplySourceMode: true, affiliateOfferGlobalSwitch: true, ownedContentDistribution: true, ownedContentSourceTypes: ["website","note","newsletter","other"] }, affiliateDistributionRuntime, nextAction: "Use get_generation_work for drafts, get_owned_content_distribution_work for owned media, get_product_discovery_work for Amazon products, or get_affiliate_reply_work for contextual affiliate distribution." });
  });
  server.registerTool("list_accounts", { description: "List sanitized accounts with no credentials. Read only.", inputSchema: { page, limit }, annotations: { readOnlyHint: true } }, async ({ page, limit }) => text({ items: (await getAccounts()).slice((page - 1) * limit, page * limit).map((account) => { const safe = { ...account } as Record<string, unknown>; delete safe.token_meta; delete safe.credentials; return safe; }), page, limit }));
  server.registerTool("get_account", { description: "Get sanitized account configuration. Read only.", inputSchema: { accountId: z.string().min(1) }, annotations: { readOnlyHint: true } }, async ({ accountId }) => { const a = await getAccount(accountId); if (!a) throw new Error("Account not found."); const safe = { ...a } as Record<string, unknown>; delete safe.token_meta; delete safe.credentials; return text({ ...safe, nextAction: "Use get_generation_work before creating drafts." }); });
  server.registerTool("get_generation_work", { description: "Return current character version and exact number of drafts to create (maximum inventory is five), plus owned-content distribution context when configured. Read only.", inputSchema: { accountId: z.string().min(1) }, annotations: { readOnlyHint: true } }, async ({ accountId }) => { const a = await getAccount(accountId); if (!a) throw new Error("Account not found."); const version = getCharacterVersion(a); const [usable, ownedContent] = await Promise.all([getUsableDraftsByAccountId(accountId, version), getOwnedContentDistributionWork(accountId, 12)]); return text({ accountId, characterVersion: version, usableDraftCount: usable.length, neededCount: Math.max(0, 5 - usable.length), ownedContent: { sources: ownedContent.sources, candidates: ownedContent.candidates, summary: ownedContent.summary, sourceAbstraction: ownedContent.sourceAbstraction }, nextAction: usable.length < 5 ? "Generate text locally; when using an owned-content candidate, include its canonical_url and pass ownedContent.itemId to create_drafts." : "No action needed." }); });
  server.registerTool("list_drafts", { description: "List drafts for an account. Read only.", inputSchema: { accountId: z.string().min(1), page, limit }, annotations: { readOnlyHint: true } }, async ({ accountId, page, limit }) => { const snap = await adminDb.collection("drafts").where("target_account_id", "==", accountId).get(); const items = snap.docs.map(d => ({ id: d.id, ...d.data() }) as { id: string; updated_at?: string }).sort((a,b) => String(b.updated_at).localeCompare(String(a.updated_at))); return text({ items: items.slice((page - 1) * limit, page * limit), page, limit }); });
  server.registerTool("list_recent_posts", { description: "List recently synchronized posts. Read only.", inputSchema: { accountId: z.string().min(1), limit }, annotations: { readOnlyHint: true } }, async ({ accountId, limit }) => text({ items: await fetchRecentPosts(accountId, limit) }));
  server.registerTool("get_schedule", { description: "Return account schedules. Read only.", inputSchema: {}, annotations: { readOnlyHint: true } }, async () => text({ timezone: "Asia/Tokyo", items: (await getAccounts()).map(a => ({ accountId: a.id, autoPostEnabled: a.autoPostEnabled === true, postSchedule: a.postSchedule ?? [], lastPostExecutedAt: a.lastPostExecutedAt ?? null })) }));
  server.registerTool("list_guidance", { description: "List writing tips and exemplary posts. Read only. Legacy [SYSTEM] protocol records remain visible for scheduled-task compatibility; prefer get_project_context for operating protocols.", inputSchema: { accountId: z.string().optional(), limit }, annotations: { readOnlyHint: true } }, async ({ accountId, limit }) => { const tips = await adminDb.collection("tips").limit(limit).get(); const exemplary = accountId ? await adminDb.collection("accounts").doc(accountId).collection("exemplary_posts").limit(limit).get() : null; return text({ tips: tips.docs.map(d => ({ id:d.id,...d.data() })), exemplaryPosts: exemplary?.docs.map(d => ({id:d.id,...d.data()})) ?? [] }); });
  server.registerTool("get_project_context", { description: "Return the operator's persistent operating protocol in one read-only call. Falls back to the legacy Global Guidance protocol when no formal context document exists.", inputSchema: { key: projectContextKey.optional() }, annotations: { readOnlyHint: true } }, async ({ key }) => text({ ...(await getProjectContext(key ?? DEFAULT_AFFILIATE_CONTEXT_KEY)), nextAction: "Use this context as the source of truth for the current operator workflow." }));
  server.registerTool("update_project_context", { description: "Create or update a formal persistent operator protocol with optimistic revision checking. Existing legacy Guidance is retained for compatibility.", inputSchema: { key: projectContextKey.optional(), expectedRevision: z.number().int().min(0), changes: projectContextChanges, ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ key, expectedRevision, changes, idempotencyKey }) => text(await runIdempotentOperation("update_project_context", idempotencyKey, async () => ({ context: await updateProjectContext(key ?? DEFAULT_AFFILIATE_CONTEXT_KEY, expectedRevision, changes as Record<string, unknown>), nextAction: "Re-read get_project_context before another update." }))));
  server.registerTool("list_products", { description: "List catalog products. Read only.", inputSchema: { limit }, annotations: { readOnlyHint: true } }, async ({ limit }) => text({ items: (await getProductPool()).slice(0, limit) }));
  server.registerTool("get_product_discovery_work", { description: "Return the active affiliate-discovery protocol plus dedupe/lifecycle context in one read-only call. This tool never drafts, publishes, archives, or changes account settings.", inputSchema: { key: projectContextKey.optional(), productLimit: z.number().int().min(1).max(200).default(50) }, annotations: { readOnlyHint: true } }, async ({ key, productLimit }) => {
    const [contextResult, products] = await Promise.all([getProjectContext(key ?? DEFAULT_AFFILIATE_CONTEXT_KEY), getProductPool()]);
    const recent = products.slice(0, productLimit);
    const lifecycleCounts = products.reduce<Record<string, number>>((acc, product) => { const state = String(product.lifecycle_state ?? "legacy_unset"); acc[state] = (acc[state] ?? 0) + 1; return acc; }, {});
    return text({
      protocol: contextResult,
      knownAsins: products.map(product => product.asin),
      recentProducts: recent.map(product => ({ id: product.id, asin: product.asin, title: product.title, status: product.status, lifecycle_state: product.lifecycle_state ?? null, viral_score: product.viral_score ?? null, amazon_verified: product.amazon_verified ?? null, updated_at: product.updated_at })),
      summary: { returned: recent.length, catalogTotal: products.length, amazonVerified: products.filter(product => product.amazon_verified === true).length, lifecycleCounts },
      jobBoundary: { allowed: ["get_project_context", "get_product_discovery_work", "list_products", "save_product"], forbidden: ["publish_draft", "create_drafts", "update_account", "update_draft", "delete_draft", "archive_product", "delete_guidance"] },
      nextAction: "Explore public Web sources, dedupe by ASIN/product identity, verify promising items on Amazon Japan, then save candidates with save_product only."
    });
  });
  server.registerTool("get_product_performance_work", { description: "Return the affiliate performance protocol plus explicitly linked Product -> Post work. Read only.", inputSchema: { key: performanceContextKey.optional(), productLimit: z.number().int().min(1).max(200).default(100) }, annotations: { readOnlyHint: true } }, async ({ key, productLimit }) => { const [protocol, work] = await Promise.all([getProjectContext(key ?? "affiliate_product_performance_v1"), getProductPerformanceWork(productLimit)]); return text({ protocol, ...work, nextAction: "Sync posts first, evaluate due 24h/72h checkpoints, then save_product; archive only when the protocol conditions are met." }); });
  server.registerTool("list_owned_content_sources", { description: "List owned-media sources used for distribution. Source types are website, note, newsletter, and other. Read only.", inputSchema: { sourceType: ownedContentSourceType.optional(), provider: z.string().trim().max(100).optional(), accountId: z.string().trim().max(256).optional(), status: ownedContentSourceStatus.optional(), limit: z.number().int().min(1).max(200).default(50) }, annotations: { readOnlyHint: true } }, async ({ sourceType, provider, accountId, status, limit }) => text({ items: await listOwnedContentSources({ sourceType, provider, accountId, status, limit }) }));
  server.registerTool("save_owned_content_source", { description: "Create or update an owned-media source. Website is only one source type; note/newsletter/other remain first-class.", inputSchema: { id: z.string().trim().min(1).max(256).optional(), expectedUpdatedAt: z.string().trim().min(1).optional(), expectedRevision: z.number().int().min(0).optional(), source: ownedContentSourceUpdateSchema, ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ id, expectedUpdatedAt, expectedRevision, source, idempotencyKey }) => text(await runIdempotentOperation("save_owned_content_source", idempotencyKey, async () => ({ source: await saveOwnedContentSource({ id, expectedUpdatedAt, expectedRevision, source: source as Record<string, unknown> }), nextAction: "Add or sync owned content items for this source." }))));
  server.registerTool("list_owned_content_items", { description: "List owned content items without mixing them into affiliate offers or Amazon products. Read only.", inputSchema: { sourceId: z.string().trim().max(256).optional(), accountId: z.string().trim().max(256).optional(), status: ownedContentItemStatus.optional(), limit: z.number().int().min(1).max(500).default(100) }, annotations: { readOnlyHint: true } }, async ({ sourceId, accountId, status, limit }) => text({ items: await listOwnedContentItems({ sourceId, accountId, status, limit }) }));

  server.registerTool("sync_owned_content_items", { description: "Bulk upsert 1–200 owned content items from an external source such as Sites Operator or note. Read/write only; never publishes.", inputSchema: { sourceId: z.string().trim().min(1).max(256), items: z.array(z.object({ external_content_id: z.string().trim().max(512).optional(), title: z.string().trim().min(1).max(500), canonical_url: z.string().url().max(2000), status: ownedContentItemStatus.optional(), themes: z.array(z.string().trim().min(1).max(120)).max(100).optional(), allowed_account_ids: z.array(z.string().trim().min(1).max(256)).max(100).optional(), persona_fits: z.array(z.string().trim().min(1).max(300)).max(100).optional(), distribution_hooks: z.array(z.string().trim().min(1).max(1000)).max(100).optional(), published_at: z.string().trim().max(64).optional(), notes: z.string().trim().max(5000).optional() })).min(1).max(200), ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ sourceId, items, idempotencyKey }) => text(await runIdempotentOperation("sync_owned_content_items", idempotencyKey, async () => ({ ...(await syncOwnedContentItems({ sourceId, items })), nextAction: "Use get_owned_content_distribution_work to rank synced items for an account." }))));

  server.registerTool("save_owned_content_item", { description: "Create or update one owned content item. Use the canonical URL and external source/content IDs for durable attribution.", inputSchema: { id: z.string().trim().min(1).max(256).optional(), expectedUpdatedAt: z.string().trim().min(1).optional(), expectedRevision: z.number().int().min(0).optional(), item: ownedContentItemUpdateSchema, ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ id, expectedUpdatedAt, expectedRevision, item, idempotencyKey }) => text(await runIdempotentOperation("save_owned_content_item", idempotencyKey, async () => ({ item: await saveOwnedContentItem({ id, expectedUpdatedAt, expectedRevision, item: item as Record<string, unknown> }), nextAction: "Use get_owned_content_distribution_work to rank this item for an account." }))));
  server.registerTool("get_owned_content_distribution_work", { description: "Return eligible owned-content candidates for an account, ranked separately from affiliate offers/products. Read only.", inputSchema: { accountId: z.string().trim().min(1).max(256), limit: z.number().int().min(1).max(100).default(30) }, annotations: { readOnlyHint: true } }, async ({ accountId, limit }) => text({ ...(await getOwnedContentDistributionWork(accountId, limit)), nextAction: "Choose a candidate, write a native-persona post containing canonical_url, then create_drafts with ownedContent.itemId." }));

  server.registerTool("list_affiliate_offers", { description: "List generic affiliate offers without mixing them into the Amazon product catalog. Read only.", inputSchema: { status: affiliateOfferStatus.optional(), network: z.string().trim().max(100).optional(), category: z.string().trim().max(160).optional(), accountId: z.string().trim().max(256).optional(), platform: z.enum(["x","threads"]).optional(), kind: affiliateOfferKind.optional(), limit: z.number().int().min(1).max(200).default(50) }, annotations: { readOnlyHint: true } }, async ({ status, network, category, accountId, platform, kind, limit }) => text({ items: await listAffiliateOffers({ status, network, category, accountId, platform, kind, limit }) }));
  server.registerTool("get_affiliate_offer", { description: "Get one generic affiliate offer. Read only.", inputSchema: { id: z.string().trim().min(1).max(256) }, annotations: { readOnlyHint: true } }, async ({ id }) => { const offer = await getAffiliateOffer(id); if (!offer) throw new Error("Affiliate offer not found."); return text({ offer }); });
  server.registerTool("save_affiliate_offer", { description: "Create or update a generic affiliate offer with optimistic concurrency. New offers default to candidate and are never auto-activated.", inputSchema: { id: z.string().trim().min(1).max(256).optional(), expectedUpdatedAt: z.string().trim().min(1).optional(), expectedRevision: z.number().int().min(0).optional(), offer: affiliateOfferUpdateSchema, ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ id, expectedUpdatedAt, expectedRevision, offer, idempotencyKey }) => text(await runIdempotentOperation("save_affiliate_offer", idempotencyKey, async () => ({ offer: await saveAffiliateOffer({ id, expectedUpdatedAt, expectedRevision, offer: offer as Record<string, unknown> }), nextAction: "Keep candidate/pending_approval offers inactive until the affiliate URL, disclosure and program approval are confirmed." }))));
  server.registerTool("archive_affiliate_offer", { description: "Archive rather than delete an affiliate offer.", inputSchema: { id: z.string().trim().min(1).max(256), expectedUpdatedAt: z.string().trim().min(1), reason: z.string().trim().min(1).max(1000).optional(), ...write }, annotations: { readOnlyHint: false, destructiveHint: true } }, async ({ id, expectedUpdatedAt, reason, idempotencyKey }) => text(await runIdempotentOperation("archive_affiliate_offer", idempotencyKey, async () => ({ offer: await archiveAffiliateOffer(id, expectedUpdatedAt, reason), nextAction: "Archived offers remain available for audit but are excluded from reply work." }))));
  server.registerTool("get_affiliate_reply_work", { description: "Return recent viral parent posts, account gates, contextual offer matches, and blocked offers. Read only; never publishes.", inputSchema: { accountId: z.string().trim().min(1).max(256).optional(), postLimit: z.number().int().min(1).max(50).default(20), offerLimit: z.number().int().min(1).max(200).default(50) }, annotations: { readOnlyHint: true } }, async ({ accountId, postLimit, offerLimit }) => text({ ...(await getAffiliateReplyWork({ accountId, postLimit, offerLimit })), nextAction: "Choose only an eligible active offer, write a disclosed reply containing affiliateUrl, then create_affiliate_reply_draft." }));
  server.registerTool("create_affiliate_reply_draft", { description: "Create one explicitly linked Offer -> Promo Reply -> Parent Post draft. Enforces active offer, targeting, viral thresholds, cooldowns, disclosure and affiliate URL.", inputSchema: { parentPostId: z.string().trim().min(1).max(256), offerId: z.string().trim().min(1).max(256), text: z.string().trim().min(1).max(1500), disclosure: z.string().trim().min(1).max(500), hookVersion: z.string().trim().max(128).optional(), ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ parentPostId, offerId, text: replyText, disclosure, hookVersion, idempotencyKey }) => text(await runIdempotentOperation("create_affiliate_reply_draft", idempotencyKey, async () => ({ reply: await createAffiliateReplyDraft({ parentPostId, offerId, text: replyText, disclosure, hookVersion }), nextAction: "Review the saved reply and its disclosure before publish_affiliate_reply." }))));
  server.registerTool("publish_affiliate_reply", { description: "Publish one saved affiliate reply draft through the existing X/Threads reply path. External side effects are locked before publish; ambiguous states reconcile instead of reposting.", inputSchema: { replyDraftId: z.string().trim().min(1).max(256), expectedUpdatedAt: z.string().trim().min(1), ...write }, annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: true } }, async ({ replyDraftId, expectedUpdatedAt, idempotencyKey }) => text(await runIdempotentOperation("publish_affiliate_reply", idempotencyKey, async () => await publishAffiliateReply(replyDraftId, expectedUpdatedAt))));
  server.registerTool("reconcile_affiliate_reply", { description: "Recover Offer -> Reply -> Parent attribution without reposting. Provide a known platform reply ID, or explicitly confirm that no external reply exists.", inputSchema: { replyId: z.string().trim().min(1).max(256), platformReplyId: z.string().trim().min(1).max(256).optional(), platformUrl: z.union([z.string().url().max(1500), z.literal("")]).optional(), confirmNotPublished: z.boolean().optional(), ...write }, annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false } }, async ({ replyId, platformReplyId, platformUrl, confirmNotPublished, idempotencyKey }) => text(await runIdempotentOperation("reconcile_affiliate_reply", idempotencyKey, async () => await reconcileAffiliateReply(replyId, { platformReplyId, platformUrl, confirmNotPublished }))));
  server.registerTool("update_affiliate_offer_performance", { description: "Record manual or agent-supplied affiliate offer performance. Supports future ASP report import without requiring it now.", inputSchema: { offerId: z.string().trim().min(1).max(256), expectedUpdatedAt: z.string().trim().min(1), update: z.object({ mode: z.enum(["increment","set"]).default("increment"), parentPostImpressions: z.number().min(0).optional(), replyImpressions: z.number().min(0).optional(), likes: z.number().min(0).optional(), replies: z.number().min(0).optional(), clicks: z.number().min(0).optional(), conversions: z.number().min(0).optional(), revenue: z.number().min(0).optional(), bestHook: z.string().trim().max(1000).optional(), bestAccount: z.string().trim().max(256).optional() }), ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ offerId, expectedUpdatedAt, update, idempotencyKey }) => text(await runIdempotentOperation("update_affiliate_offer_performance", idempotencyKey, async () => ({ offer: await updateAffiliateOfferPerformance(offerId, expectedUpdatedAt, update), nextAction: "Re-read get_affiliate_offer before another performance update." }))));

  server.registerTool("create_drafts", { description: "Atomically save 1–10 agent-authored drafts, bounded by five current-version drafts. Requires current character version and idempotency key.", inputSchema: { accountId: z.string().min(1), expectedCharacterVersion: z.number().int().min(1), drafts: z.array(z.object({ text:z.string().min(1), hashtags:z.array(z.string()).max(10).optional(), overwriteSimilar:z.boolean().optional(), affiliate:z.object({ productId:z.string().trim().min(1).max(256), creativeAssetId:z.string().trim().min(1).max(256).optional() }).optional(), ownedContent:z.object({ itemId:z.string().trim().min(1).max(256) }).optional() })).min(1).max(10), ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ accountId, expectedCharacterVersion, drafts, idempotencyKey }) => text(await runIdempotentOperation("create_drafts", idempotencyKey, async () => ({ drafts: await createAgentDrafts(accountId, expectedCharacterVersion, drafts), nextAction: "Re-run get_generation_work. Owned-content attribution is stored separately from affiliate attribution." }))));
  server.registerTool("update_draft", { description: "Update an existing draft after checking updated_at. Requires idempotency key.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), text:z.string().min(1).optional(), hashtags:z.array(z.string()).max(10).optional(), status:z.enum(["draft","scheduled"]).optional(), ...write }, annotations: { readOnlyHint:false, destructiveHint:false } }, async ({ draftId, expectedUpdatedAt, idempotencyKey, ...changes }) => text(await runIdempotentOperation("update_draft", idempotencyKey, async () => { const ref=adminDb.collection("drafts").doc(draftId); await assertUpdated(ref, expectedUpdatedAt); await ref.update({ ...changes, updated_at: DateTime.utc().toISO() }); return { draftId, status:"updated", nextAction:"Review or publish the existing draft." }; })));
  server.registerTool("delete_draft", { description: "Permanently delete one draft after checking updated_at. Requires idempotency key.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), ...write }, annotations: { readOnlyHint:false, destructiveHint:true } }, async ({ draftId, expectedUpdatedAt, idempotencyKey }) => text(await runIdempotentOperation("delete_draft", idempotencyKey, async () => { const ref=adminDb.collection("drafts").doc(draftId); await assertUpdated(ref, expectedUpdatedAt); await ref.delete(); return {draftId,status:"deleted",nextAction:"Recheck generation work."}; })));
  server.registerTool("publish_draft", { description: "Publish one existing current-version draft only. Direct arbitrary-text posts are forbidden. Requires idempotency key and expected updated_at.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), ...write }, annotations: { readOnlyHint:false, destructiveHint:true, openWorldHint:true } }, async ({ draftId, expectedUpdatedAt, idempotencyKey }) => text(await runIdempotentOperation("publish_draft", idempotencyKey, async () => ({ publishedPost: await publishExistingDraft(draftId, expectedUpdatedAt), nextAction:"Sync later to refresh metrics; affiliate Product -> Post linking is durable or marked pending for reconciliation." }))));
  server.registerTool("update_account", { description: "Update non-secret account settings after checking updated_at. Requires idempotency key.", inputSchema: { accountId:z.string().min(1), expectedUpdatedAt:z.string().min(1), changes:z.record(z.string(), z.unknown()), ...write }, annotations: { readOnlyHint:false, destructiveHint:false } }, async ({ accountId, expectedUpdatedAt, changes, idempotencyKey }) => text(await runIdempotentOperation("update_account", idempotencyKey, async () => { const ref=adminDb.collection("accounts").doc(accountId); await assertUpdated(ref, expectedUpdatedAt); await updateAccount(accountId, changes as never); return {accountId,status:"updated",nextAction:"Refresh generation work if the character sheet changed."}; })));
  server.registerTool("sync_posts", { description: "Synchronize recent platform posts. Requires idempotency key and may call external platforms.", inputSchema: { accountIds:z.array(z.string()).max(20).optional(), maxPosts:z.number().int().min(1).max(100).optional(), ...write }, annotations: { readOnlyHint:false, openWorldHint:true } }, async ({ accountIds,maxPosts,idempotencyKey }) => text(await runIdempotentOperation("sync_posts", idempotencyKey, async () => ({result: await syncPostsForAllAccounts({accountIds,maxPosts}),nextAction:"Review health, affiliate reconciliation, or generation work."}))));
  server.registerTool("save_product", { description: "Create or update a product catalog item. Known affiliate fields are validated while unknown extension fields are preserved. Requires idempotency key; update requires expected updated_at.", inputSchema: { id:z.string().optional(), expectedUpdatedAt:z.string().optional(), product:productCatalogUpdateSchema, ...write }, annotations:{readOnlyHint:false,destructiveHint:false}}, async ({id,expectedUpdatedAt,product,idempotencyKey}) => text(await runIdempotentOperation("save_product",idempotencyKey,async()=> { if(id){if(!expectedUpdatedAt) throw new Error("expectedUpdatedAt is required for updates."); await assertUpdated(adminDb.collection("products").doc(id),expectedUpdatedAt); const normalized=normalizeProductCatalogInput(product as Record<string, unknown>,"update"); return {product:await updateProductPoolItem(id,normalized as never),nextAction:"Continue the product lifecycle without changing posting jobs."};} const normalized=normalizeProductCatalogInput(product as Record<string, unknown>,"create"); return {product:await createProductPoolItem(normalized as never),nextAction:"Use get_product_discovery_work to refresh dedupe and lifecycle context."};})));
  server.registerTool("archive_product", { description: "Archive rather than delete a product. Requires idempotency key and expected updated_at.", inputSchema:{id:z.string().min(1),expectedUpdatedAt:z.string().min(1),reason:z.string().trim().min(1).max(500).optional(),...write},annotations:{readOnlyHint:false,destructiveHint:true}},async({id,expectedUpdatedAt,reason,idempotencyKey})=>text(await runIdempotentOperation("archive_product",idempotencyKey,async()=>{await assertUpdated(adminDb.collection("products").doc(id),expectedUpdatedAt); return {product:await updateProductPoolItem(id,{status:"archived",...(reason?{archive_reason:reason}:{})}),nextAction:"Product remains retained for audit."};})));
  // Guidance mutations are deliberately explicit and audited; these tools avoid any credential fields.
  server.registerTool("save_guidance", { description:"Create or update a tip or exemplary post. Requires idempotency key; updates require expected updated_at.", inputSchema:{kind:z.enum(["tip","exemplary"]),accountId:z.string().optional(),id:z.string().optional(),expectedUpdatedAt:z.string().optional(),data:z.record(z.string(), z.unknown()),...write},annotations:{readOnlyHint:false,destructiveHint:false}},async({kind,accountId,id,expectedUpdatedAt,data,idempotencyKey})=>text(await runIdempotentOperation("save_guidance",idempotencyKey,async()=>{const col=kind==="tip"?adminDb.collection("tips"):(accountId?adminDb.collection("accounts").doc(accountId).collection("exemplary_posts"):null);if(!col) throw new Error("accountId is required for exemplary guidance.");const now=DateTime.utc().toISO();const ref=id?col.doc(id):col.doc();if(id){if(!expectedUpdatedAt)throw new Error("expectedUpdatedAt is required for updates.");await assertUpdated(ref,expectedUpdatedAt);await ref.update({...data,updated_at:now});}else await ref.set({...data,created_at:now,updated_at:now});return {id:ref.id,status:"saved",nextAction:"Use get_generation_work."};})));
  server.registerTool("delete_guidance", { description:"Permanently delete a tip or exemplary post after checking updated_at. Requires idempotency key.", inputSchema:{kind:z.enum(["tip","exemplary"]),accountId:z.string().optional(),id:z.string().min(1),expectedUpdatedAt:z.string().min(1),...write},annotations:{readOnlyHint:false,destructiveHint:true}},async({kind,accountId,id,expectedUpdatedAt,idempotencyKey})=>text(await runIdempotentOperation("delete_guidance",idempotencyKey,async()=>{const col=kind==="tip"?adminDb.collection("tips"):(accountId?adminDb.collection("accounts").doc(accountId).collection("exemplary_posts"):null);if(!col)throw new Error("accountId is required for exemplary guidance.");const ref=col.doc(id);await assertUpdated(ref,expectedUpdatedAt);await ref.delete();return{id,status:"deleted",nextAction:"Regenerate drafts if needed."};})));
  return server;
}
