import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { DateTime } from "luxon";
import { adminDb } from "@/lib/firebase/admin";
import { getAccounts, getAccount, getUsableDraftsByAccountId, fetchRecentPosts } from "@/lib/services/firestore.server";
import { createAgentDrafts } from "@/lib/services/draft-service";
import { runIdempotentOperation } from "@/lib/services/agent-operation-service";
import { getCharacterVersion } from "@/lib/character-version";
import { updateAccount } from "@/lib/services/account-service";
import { syncPostsForAllAccounts } from "@/lib/services/sync-service";
import { getProductPool, createProductPoolItem, updateProductPoolItem } from "@/lib/services/product-pool-service";
import { publishExistingDraft } from "@/lib/services/scheduler-service";

const text = (value: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] });
const page = z.number().int().min(1).default(1); const limit = z.number().int().min(1).max(50).default(20);
const write = { idempotencyKey: z.string().min(1).max(128) };
async function assertUpdated(ref: FirebaseFirestore.DocumentReference, expected: string) {
  const snap = await ref.get(); if (!snap.exists) throw new Error("Document not found.");
  if (snap.data()?.updated_at !== expected) throw new Error("updated_at conflict: refresh and retry.");
  return snap;
}

export function createTweetsMcpServer() {
  const server = new McpServer({ name: "tweets-operator", version: "1.0.0" });
  server.registerTool("get_system_health", { description: "Summarize connection and current-version draft inventory. Read only.", inputSchema: {} , annotations: { readOnlyHint: true }}, async () => {
    const accounts = await getAccounts(); const inventory = await Promise.all(accounts.map(async (a) => ({ accountId: a.id, usableDrafts: (await getUsableDraftsByAccountId(a.id, getCharacterVersion(a))).length })));
    return text({ status: "ok", accounts: accounts.length, inventory, nextAction: "Use get_generation_work for accounts below five drafts." });
  });
  server.registerTool("list_accounts", { description: "List sanitized accounts with no credentials. Read only.", inputSchema: { page, limit }, annotations: { readOnlyHint: true } }, async ({ page, limit }) => text({ items: (await getAccounts()).slice((page - 1) * limit, page * limit).map((account) => { const safe = { ...account } as Record<string, unknown>; delete safe.token_meta; delete safe.credentials; return safe; }), page, limit }));
  server.registerTool("get_account", { description: "Get sanitized account configuration. Read only.", inputSchema: { accountId: z.string().min(1) }, annotations: { readOnlyHint: true } }, async ({ accountId }) => { const a = await getAccount(accountId); if (!a) throw new Error("Account not found."); const safe = { ...a } as Record<string, unknown>; delete safe.token_meta; delete safe.credentials; return text({ ...safe, nextAction: "Use get_generation_work before creating drafts." }); });
  server.registerTool("get_generation_work", { description: "Return current character version and exact number of drafts to create (maximum inventory is five). Read only.", inputSchema: { accountId: z.string().min(1) }, annotations: { readOnlyHint: true } }, async ({ accountId }) => { const a = await getAccount(accountId); if (!a) throw new Error("Account not found."); const version = getCharacterVersion(a); const usable = await getUsableDraftsByAccountId(accountId, version); return text({ accountId, characterVersion: version, usableDraftCount: usable.length, neededCount: Math.max(0, 5 - usable.length), nextAction: usable.length < 5 ? "Generate text locally, then call create_drafts." : "No action needed." }); });
  server.registerTool("list_drafts", { description: "List drafts for an account. Read only.", inputSchema: { accountId: z.string().min(1), page, limit }, annotations: { readOnlyHint: true } }, async ({ accountId, page, limit }) => { const snap = await adminDb.collection("drafts").where("target_account_id", "==", accountId).get(); const items = snap.docs.map(d => ({ id: d.id, ...d.data() }) as { id: string; updated_at?: string }).sort((a,b) => String(b.updated_at).localeCompare(String(a.updated_at))); return text({ items: items.slice((page - 1) * limit, page * limit), page, limit }); });
  server.registerTool("list_recent_posts", { description: "List recently synchronized posts. Read only.", inputSchema: { accountId: z.string().min(1), limit }, annotations: { readOnlyHint: true } }, async ({ accountId, limit }) => text({ items: await fetchRecentPosts(accountId, limit) }));
  server.registerTool("get_schedule", { description: "Return account schedules. Read only.", inputSchema: {}, annotations: { readOnlyHint: true } }, async () => text({ timezone: "Asia/Tokyo", items: (await getAccounts()).map(a => ({ accountId: a.id, autoPostEnabled: a.autoPostEnabled === true, postSchedule: a.postSchedule ?? [], lastPostExecutedAt: a.lastPostExecutedAt ?? null })) }));
  server.registerTool("list_guidance", { description: "List writing tips and exemplary posts. Read only.", inputSchema: { accountId: z.string().optional(), limit }, annotations: { readOnlyHint: true } }, async ({ accountId, limit }) => { const tips = await adminDb.collection("tips").limit(limit).get(); const exemplary = accountId ? await adminDb.collection("accounts").doc(accountId).collection("exemplary_posts").limit(limit).get() : null; return text({ tips: tips.docs.map(d => ({ id:d.id,...d.data() })), exemplaryPosts: exemplary?.docs.map(d => ({id:d.id,...d.data()})) ?? [] }); });
  server.registerTool("list_products", { description: "List catalog products. Read only.", inputSchema: { limit }, annotations: { readOnlyHint: true } }, async ({ limit }) => text({ items: (await getProductPool()).slice(0, limit) }));
  server.registerTool("create_drafts", { description: "Atomically save 1–10 agent-authored drafts, bounded by five current-version drafts. Requires current character version and idempotency key.", inputSchema: { accountId: z.string().min(1), expectedCharacterVersion: z.number().int().min(1), drafts: z.array(z.object({ text:z.string().min(1), hashtags:z.array(z.string()).max(10).optional(), overwriteSimilar:z.boolean().optional() })).min(1).max(10), ...write }, annotations: { readOnlyHint: false, destructiveHint: false } }, async ({ accountId, expectedCharacterVersion, drafts, idempotencyKey }) => text(await runIdempotentOperation("create_drafts", idempotencyKey, async () => ({ drafts: await createAgentDrafts(accountId, expectedCharacterVersion, drafts), nextAction: "Re-run get_generation_work." }))));
  server.registerTool("update_draft", { description: "Update an existing draft after checking updated_at. Requires idempotency key.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), text:z.string().min(1).optional(), hashtags:z.array(z.string()).max(10).optional(), status:z.enum(["draft","scheduled"]).optional(), ...write }, annotations: { readOnlyHint:false, destructiveHint:false } }, async ({ draftId, expectedUpdatedAt, idempotencyKey, ...changes }) => text(await runIdempotentOperation("update_draft", idempotencyKey, async () => { const ref=adminDb.collection("drafts").doc(draftId); await assertUpdated(ref, expectedUpdatedAt); await ref.update({ ...changes, updated_at: DateTime.utc().toISO() }); return { draftId, status:"updated", nextAction:"Review or publish the existing draft." }; })));
  server.registerTool("delete_draft", { description: "Permanently delete one draft after checking updated_at. Requires idempotency key.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), ...write }, annotations: { readOnlyHint:false, destructiveHint:true } }, async ({ draftId, expectedUpdatedAt, idempotencyKey }) => text(await runIdempotentOperation("delete_draft", idempotencyKey, async () => { const ref=adminDb.collection("drafts").doc(draftId); await assertUpdated(ref, expectedUpdatedAt); await ref.delete(); return {draftId,status:"deleted",nextAction:"Recheck generation work."}; })));
  server.registerTool("publish_draft", { description: "Publish one existing current-version draft only. Direct arbitrary-text posts are forbidden. Requires idempotency key and expected updated_at.", inputSchema: { draftId:z.string().min(1), expectedUpdatedAt:z.string().min(1), ...write }, annotations: { readOnlyHint:false, destructiveHint:true, openWorldHint:true } }, async ({ draftId, expectedUpdatedAt, idempotencyKey }) => text(await runIdempotentOperation("publish_draft", idempotencyKey, async () => ({ publishedPost: await publishExistingDraft(draftId, expectedUpdatedAt), nextAction:"Sync later to refresh metrics." }))));
  server.registerTool("update_account", { description: "Update non-secret account settings after checking updated_at. Requires idempotency key.", inputSchema: { accountId:z.string().min(1), expectedUpdatedAt:z.string().min(1), changes:z.record(z.string(), z.unknown()), ...write }, annotations: { readOnlyHint:false, destructiveHint:false } }, async ({ accountId, expectedUpdatedAt, changes, idempotencyKey }) => text(await runIdempotentOperation("update_account", idempotencyKey, async () => { const ref=adminDb.collection("accounts").doc(accountId); await assertUpdated(ref, expectedUpdatedAt); await updateAccount(accountId, changes as never); return {accountId,status:"updated",nextAction:"Refresh generation work if the character sheet changed."}; })));
  server.registerTool("sync_posts", { description: "Synchronize recent platform posts. Requires idempotency key and may call external platforms.", inputSchema: { accountIds:z.array(z.string()).max(20).optional(), maxPosts:z.number().int().min(1).max(100).optional(), ...write }, annotations: { readOnlyHint:false, openWorldHint:true } }, async ({ accountIds,maxPosts,idempotencyKey }) => text(await runIdempotentOperation("sync_posts", idempotencyKey, async () => ({result: await syncPostsForAllAccounts({accountIds,maxPosts}),nextAction:"Review health or generation work."}))));
  server.registerTool("save_product", { description: "Create or update a product catalog item. Requires idempotency key; update requires expected updated_at.", inputSchema: { id:z.string().optional(), expectedUpdatedAt:z.string().optional(), product:z.record(z.string(), z.unknown()), ...write }, annotations:{readOnlyHint:false,destructiveHint:false}}, async ({id,expectedUpdatedAt,product,idempotencyKey}) => text(await runIdempotentOperation("save_product",idempotencyKey,async()=> { if(id){if(!expectedUpdatedAt) throw new Error("expectedUpdatedAt is required for updates."); await assertUpdated(adminDb.collection("products").doc(id),expectedUpdatedAt); return {product:await updateProductPoolItem(id,product as never),nextAction:"Review product assignment."};} return {product:await createProductPoolItem(product as never),nextAction:"Review product assignment."};})));
  server.registerTool("archive_product", { description: "Archive rather than delete a product. Requires idempotency key and expected updated_at.", inputSchema:{id:z.string().min(1),expectedUpdatedAt:z.string().min(1),...write},annotations:{readOnlyHint:false,destructiveHint:true}},async({id,expectedUpdatedAt,idempotencyKey})=>text(await runIdempotentOperation("archive_product",idempotencyKey,async()=>{await assertUpdated(adminDb.collection("products").doc(id),expectedUpdatedAt); return {product:await updateProductPoolItem(id,{status:"archived"}),nextAction:"Product remains retained for audit."};})));
  // Guidance mutations are deliberately explicit and audited; these tools avoid any credential fields.
  server.registerTool("save_guidance", { description:"Create or update a tip or exemplary post. Requires idempotency key; updates require expected updated_at.", inputSchema:{kind:z.enum(["tip","exemplary"]),accountId:z.string().optional(),id:z.string().optional(),expectedUpdatedAt:z.string().optional(),data:z.record(z.string(), z.unknown()),...write},annotations:{readOnlyHint:false,destructiveHint:false}},async({kind,accountId,id,expectedUpdatedAt,data,idempotencyKey})=>text(await runIdempotentOperation("save_guidance",idempotencyKey,async()=>{const col=kind==="tip"?adminDb.collection("tips"):(accountId?adminDb.collection("accounts").doc(accountId).collection("exemplary_posts"):null);if(!col) throw new Error("accountId is required for exemplary guidance.");const now=DateTime.utc().toISO();const ref=id?col.doc(id):col.doc();if(id){if(!expectedUpdatedAt)throw new Error("expectedUpdatedAt is required for updates.");await assertUpdated(ref,expectedUpdatedAt);await ref.update({...data,updated_at:now});}else await ref.set({...data,created_at:now,updated_at:now});return {id:ref.id,status:"saved",nextAction:"Use get_generation_work."};})));
  server.registerTool("delete_guidance", { description:"Permanently delete a tip or exemplary post after checking updated_at. Requires idempotency key.", inputSchema:{kind:z.enum(["tip","exemplary"]),accountId:z.string().optional(),id:z.string().min(1),expectedUpdatedAt:z.string().min(1),...write},annotations:{readOnlyHint:false,destructiveHint:true}},async({kind,accountId,id,expectedUpdatedAt,idempotencyKey})=>text(await runIdempotentOperation("delete_guidance",idempotencyKey,async()=>{const col=kind==="tip"?adminDb.collection("tips"):(accountId?adminDb.collection("accounts").doc(accountId).collection("exemplary_posts"):null);if(!col)throw new Error("accountId is required for exemplary guidance.");const ref=col.doc(id);await assertUpdated(ref,expectedUpdatedAt);await ref.delete();return{id,status:"deleted",nextAction:"Regenerate drafts if needed."};})));
  return server;
}
